dataset:
    base_path: "./data"
    dataset_name: "plant_phenotyping"

image:
    out_stride: 16
    base_size: 256
    crop_size: 256

network:
    backbone: "resnet"
    sync_bn: false
    freeze_bn: true
    use_cuda: true
    num_classes: 2

training:
    workers: 0
    loss_type: "ce"
    epochs: 50
    start_epoch: 0
    batch_size: 2
    use_balanced_weights: true
    lr: 0.0005
    lr_scheduler: "poly"
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: false
    weights_initialization:
        use_pretrained_weights: false
        restore_from: ""
    train_on_subset:
        enabled: false
        dataset_fraction: 1.0
    tensorboard:
        enabled: false
        log_dir: "./tensorboard/"
    no_val: false
    val_interval: 1